/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ItemCollapse {
    'open': boolean;
    'title': string;
  }
}

declare global {


  interface HTMLItemCollapseElement extends Components.ItemCollapse, HTMLStencilElement {}
  var HTMLItemCollapseElement: {
    prototype: HTMLItemCollapseElement;
    new (): HTMLItemCollapseElement;
  };
  interface HTMLElementTagNameMap {
    'item-collapse': HTMLItemCollapseElement;
  }
}

declare namespace LocalJSX {
  interface ItemCollapse {
    'open'?: boolean;
    'title'?: string;
  }

  interface IntrinsicElements {
    'item-collapse': ItemCollapse;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'item-collapse': LocalJSX.ItemCollapse & JSXBase.HTMLAttributes<HTMLItemCollapseElement>;
    }
  }
}


